added multiple languages support

diff --git a/backend/pipeline-1/Dockerfile b/backend/pipeline-1/Dockerfile
--- a/backend/pipeline-1/Dockerfile
+++ b/backend/pipeline-1/Dockerfile
@@ -6,5 +6,6 @@ RUN pip install --no-cache-dir \
     torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu
 RUN pip install --no-cache-dir -r requirements.txt
 COPY . .
-RUN test -d legal_bert_local || (echo "ERROR: legal_bert_local/ not found. Run download script first." && exit 1)
+# RUN test -d legal_bert_local || (echo "ERROR: legal_bert_local/ not found. Run download script first." && exit 1)
+RUN mkdir -p legal_bert_local
 CMD ["python", "scheduler.py"]
